# Generated by Django 3.1a1 on 2020-06-14 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Decription', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=5000)),
                ('Article_image', models.FileField(blank=True, upload_to='post_image')),
                ('date', models.DateField()),
                ('writer', models.CharField(max_length=50)),
                ('Article_Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.categoary')),
            ],
        ),
    ]
