# Generated by Django 3.1a1 on 2020-06-18 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_article_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='writer',
        ),
    ]
