# Generated by Django 3.1a1 on 2020-06-18 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_article_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Article_image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
