# Generated by Django 3.1a1 on 2020-06-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200618_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Article_image',
            field=models.FileField(null=True, upload_to='post_image'),
        ),
    ]
