# Generated by Django 3.1a1 on 2020-06-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200618_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Article_image',
            field=models.FileField(default='/static/post_image/IMG_0718.jpg', null=True, upload_to='post_image'),
        ),
    ]
