# Generated by Django 3.1a1 on 2020-06-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200618_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Article_image',
            field=models.FileField(blank=True, upload_to='post_image'),
        ),
    ]
