# Generated by Django 3.1a1 on 2020-06-19 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200618_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Decription',
            new_name='Description',
        ),
    ]
